spring:
  profiles:
    active: henry
    include:
      - mybatis
      - redis

#微信配置相关
weixin:
  config:
    appId: wxf9a70d30a6944069185
    secret: b735fc511979462ef3e2dd7f8e80ab581459
  code2session:
    url: https://api.weixin.qq.com/sns/jscode2session?appid={appId}&secret={secret}&js_code={code}&grant_type=authorization_code
